/** @format */

export const recipesType = {
  GET_RECIPES_BY_TYPE: 'GET_RECIPES_BY_TYPE',
  GET_RECIPES_BY_USER_ID: 'GET_RECIPES_BY_USER_ID',
  GET_RECIPE_BY_ID: 'GET_RECIPE_BY_ID',
  SEARCH_RECIPES_BY_NAME: 'SEARCH_RECIPES_BY_NAME',
};
