/** @format */

export const recipesType = {
  GET_RECIPES_BY_TYPE: 'GET_RECIPES_BY_TYPE',
  GET_RECIPES_BY_USER_ID: 'GET_RECIPES_BY_USER_ID',
  GET_RECIPE_BY_ID: 'GET_RECIPE_BY_ID',
  SEARCH_RECIPES_BY_NAME: 'SEARCH_RECIPES_BY_NAME',
  CREATE_RECIPE: 'CREATE_RECIPE',
  UPDATE_RECIPE: 'UPDATE_RECIPE',
  DELETE_RECIPE: 'DELETE_RECIPE',
  GET_FAVORITE_RECIPES: 'GET_FAVORITE_RECIPES',
  FAV_RECIPE: 'FAV_RECIPE',
  UN_FAV_RECIPE: 'UN_FAV_RECIPE',
};
