export const userType = {
  ADMIN_GET_USER_BY_ID: 'ADMIN_GET_USER_BY_ID',
  ADMIN_GET_ALL_USERS: 'ADMIN_GET_ALL_USERS',
  ADMIN_UDPATE_USER: 'ADMIN_UDPATE_USER',
  ADMIN_DELETE_USER: 'ADMIN_DELETE_USER',
};
